-- -- SQLite
-- select dnsId_id, count() as d from app_wordpress 
-- where 1=1 
-- group by dnsID_id
-- having d > 1

-- DELETE FROM app_wordpress 
-- WHERE rowid NOT IN (
--     SELECT MIN(rowid) 
--     FROM app_wordpress 
--     GROUP BY dnsId_id
-- );