# Generated by Django 5.1.7 on 2025-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DNS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dns", models.CharField(max_length=200)),
                ("tld", models.CharField(max_length=10)),
                ("ip", models.CharField(max_length=200)),
                ("data", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
