# Generated by Django 5.1.7 on 2025-03-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Http",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("http", models.BooleanField()),
                ("https", models.BooleanField()),
                ("checked", models.DateTimeField(auto_now=True)),
                (
                    "dnsId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dns"
                    ),
                ),
            ],
        ),
    ]
