# Generated by Django 5.1.7 on 2025-03-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_setting_http"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wordpress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=200)),
                (
                    "dnsId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dns"
                    ),
                ),
            ],
        ),
    ]
