# Generated by Django 5.1.7 on 2025-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_wordpress"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordpress",
            name="user_enumeration",
            field=models.BooleanField(null=True),
        ),
    ]
