# Generated by Django 5.1.7 on 2025-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_tlds_tld"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dns",
            old_name="data",
            new_name="date",
        ),
        migrations.AddField(
            model_name="setting",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wordpress",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
