# Generated by Django 5.1.7 on 2025-03-10 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_data_dns_date_setting_date_wordpress_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="http",
            name="has_security_txt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="http",
            name="security_txt",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="security.txt"
            ),
        ),
        migrations.AddField(
            model_name="wordpress",
            name="php",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="PHP-Version"
            ),
        ),
        migrations.AlterField(
            model_name="dns",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="dns",
            name="dns",
            field=models.CharField(max_length=200, verbose_name="DNS"),
        ),
        migrations.AlterField(
            model_name="dns",
            name="ip",
            field=models.CharField(max_length=200, verbose_name="IP-Adress"),
        ),
        migrations.AlterField(
            model_name="dns",
            name="tld",
            field=models.CharField(max_length=10, verbose_name="TLD"),
        ),
        migrations.AlterField(
            model_name="wordpress",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="wordpress",
            name="dnsId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.dns",
                verbose_name="ID",
            ),
        ),
    ]
