# Generated by Django 5.1.7 on 2025-03-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_http_has_security_txt_http_security_txt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("mail", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CRM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.CharField(max_length=200)),
                (
                    "dns",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dns"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.vendor",
                        verbose_name="Vendor",
                    ),
                ),
            ],
        ),
    ]
