# Generated by Django 5.1.7 on 2025-03-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_vendor_crm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crm",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.vendor",
                verbose_name="Vendor",
            ),
        ),
    ]
