# Generated by Django 5.1.7 on 2025-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_crm_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHPVersion",
            fields=[
                (
                    "version",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("release_date", models.DateField()),
                ("active_support", models.DateField()),
                ("security_support", models.DateField()),
                ("end_of_life", models.DateField()),
            ],
        ),
    ]
