# Generated by Django 5.1.7 on 2025-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_phpversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordpress",
            name="xml_rpc",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
