# Generated by Django 5.1.7 on 2025-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_wordpress_xml_rpc"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordpress",
            name="open_directory",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
