# Generated by Django 5.1.7 on 2025-03-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_wordpress_open_directory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubDomains",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdomain", models.CharField(max_length=200)),
                ("ip", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "dnsId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dns"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubdomainsTop100Liste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.CharField(max_length=200)),
                (
                    "tld",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.tld"
                    ),
                ),
            ],
        ),
    ]
