# Generated by Django 5.1.7 on 2025-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_subdomains_subdomainstop100liste"),
    ]

    operations = [
        migrations.AddField(
            model_name="dns",
            name="has_subdomains",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
