# Generated by Django 5.1.7 on 2025-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_dns_has_subdomains"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("module", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
